/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BodyPartialUpdateOneByPrimaryKeyProductsIdPatch model module.
 * @module model/BodyPartialUpdateOneByPrimaryKeyProductsIdPatch
 * @version 0.1.0
 */
export class BodyPartialUpdateOneByPrimaryKeyProductsIdPatch {
  /**
   * Constructs a new <code>BodyPartialUpdateOneByPrimaryKeyProductsIdPatch</code>.
   * @alias module:model/BodyPartialUpdateOneByPrimaryKeyProductsIdPatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BodyPartialUpdateOneByPrimaryKeyProductsIdPatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BodyPartialUpdateOneByPrimaryKeyProductsIdPatch} obj Optional instance to populate.
   * @return {module:model/BodyPartialUpdateOneByPrimaryKeyProductsIdPatch} The populated <code>BodyPartialUpdateOneByPrimaryKeyProductsIdPatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BodyPartialUpdateOneByPrimaryKeyProductsIdPatch();
      if (data.hasOwnProperty('stripe_product'))
        obj.stripeProduct = ApiClient.convertToType(data['stripe_product'], 'String');
      if (data.hasOwnProperty('stripe_price'))
        obj.stripePrice = ApiClient.convertToType(data['stripe_price'], 'String');
      if (data.hasOwnProperty('display_price'))
        obj.displayPrice = ApiClient.convertToType(data['display_price'], 'Number');
      if (data.hasOwnProperty('deck_id'))
        obj.deckId = ApiClient.convertToType(data['deck_id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} stripeProduct
 */
BodyPartialUpdateOneByPrimaryKeyProductsIdPatch.prototype.stripeProduct = undefined;

/**
 * @member {String} stripePrice
 */
BodyPartialUpdateOneByPrimaryKeyProductsIdPatch.prototype.stripePrice = undefined;

/**
 * @member {Number} displayPrice
 */
BodyPartialUpdateOneByPrimaryKeyProductsIdPatch.prototype.displayPrice = undefined;

/**
 * @member {Number} deckId
 */
BodyPartialUpdateOneByPrimaryKeyProductsIdPatch.prototype.deckId = undefined;

