/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {RangeToComparisonOperators} from './RangeToComparisonOperators';

/**
 * The DateJoinedToComparisonOperator3 model module.
 * @module model/DateJoinedToComparisonOperator3
 * @version 0.1.0
 */
export class DateJoinedToComparisonOperator3 extends RangeToComparisonOperators {
  /**
   * Constructs a new <code>DateJoinedToComparisonOperator3</code>.
   * @alias module:model/DateJoinedToComparisonOperator3
   * @class
   * @extends module:model/RangeToComparisonOperators
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DateJoinedToComparisonOperator3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DateJoinedToComparisonOperator3} obj Optional instance to populate.
   * @return {module:model/DateJoinedToComparisonOperator3} The populated <code>DateJoinedToComparisonOperator3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DateJoinedToComparisonOperator3();
      RangeToComparisonOperators.constructFromObject(data, obj);
    }
    return obj;
  }
}
