/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TarotSpreadUpdateManyResponseItemModel} from './TarotSpreadUpdateManyResponseItemModel';

/**
 * The TarotSpreadUpdateManyItemListResponseModel model module.
 * @module model/TarotSpreadUpdateManyItemListResponseModel
 * @version 0.1.0
 */
export class TarotSpreadUpdateManyItemListResponseModel extends Array {
  /**
   * Constructs a new <code>TarotSpreadUpdateManyItemListResponseModel</code>.
   * @alias module:model/TarotSpreadUpdateManyItemListResponseModel
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TarotSpreadUpdateManyItemListResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TarotSpreadUpdateManyItemListResponseModel} obj Optional instance to populate.
   * @return {module:model/TarotSpreadUpdateManyItemListResponseModel} The populated <code>TarotSpreadUpdateManyItemListResponseModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TarotSpreadUpdateManyItemListResponseModel();
      ApiClient.constructFromObject(data, obj, 'TarotSpreadUpdateManyResponseItemModel');
    }
    return obj;
  }
}
