/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TarotProductDeleteOneResponseModel model module.
 * @module model/TarotProductDeleteOneResponseModel
 * @version 0.1.0
 */
export class TarotProductDeleteOneResponseModel {
  /**
   * Constructs a new <code>TarotProductDeleteOneResponseModel</code>.
   * auto gen by FastApi quick CRUD
   * @alias module:model/TarotProductDeleteOneResponseModel
   * @class
   * @param id {Number} 
   * @param stripeProduct {String} 
   * @param stripePrice {String} 
   * @param displayPrice {Number} 
   * @param deckId {Number} 
   */
  constructor(id, stripeProduct, stripePrice, displayPrice, deckId) {
    this.id = id;
    this.stripeProduct = stripeProduct;
    this.stripePrice = stripePrice;
    this.displayPrice = displayPrice;
    this.deckId = deckId;
  }

  /**
   * Constructs a <code>TarotProductDeleteOneResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TarotProductDeleteOneResponseModel} obj Optional instance to populate.
   * @return {module:model/TarotProductDeleteOneResponseModel} The populated <code>TarotProductDeleteOneResponseModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TarotProductDeleteOneResponseModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('stripe_product'))
        obj.stripeProduct = ApiClient.convertToType(data['stripe_product'], 'String');
      if (data.hasOwnProperty('stripe_price'))
        obj.stripePrice = ApiClient.convertToType(data['stripe_price'], 'String');
      if (data.hasOwnProperty('display_price'))
        obj.displayPrice = ApiClient.convertToType(data['display_price'], 'Number');
      if (data.hasOwnProperty('deck_id'))
        obj.deckId = ApiClient.convertToType(data['deck_id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
TarotProductDeleteOneResponseModel.prototype.id = undefined;

/**
 * @member {String} stripeProduct
 */
TarotProductDeleteOneResponseModel.prototype.stripeProduct = undefined;

/**
 * @member {String} stripePrice
 */
TarotProductDeleteOneResponseModel.prototype.stripePrice = undefined;

/**
 * @member {Number} displayPrice
 */
TarotProductDeleteOneResponseModel.prototype.displayPrice = undefined;

/**
 * @member {Number} deckId
 */
TarotProductDeleteOneResponseModel.prototype.deckId = undefined;

