/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ItemComparisonOperators', function() {
      beforeEach(function() {
        instance = FastApi.ItemComparisonOperators;
      });

      it('should create an instance of ItemComparisonOperators', function() {
        // TODO: update the code to test ItemComparisonOperators
        expect(instance).to.be.a('object');
      });

      it('should have the property equal', function() {
        expect(instance).to.have.property('equal');
        expect(instance.equal).to.be("Equal");
      });

      it('should have the property notEqual', function() {
        expect(instance).to.have.property('notEqual');
        expect(instance.notEqual).to.be("Not_equal");
      });

      it('should have the property _in', function() {
        expect(instance).to.have.property('_in');
        expect(instance._in).to.be("In");
      });

      it('should have the property notIn', function() {
        expect(instance).to.have.property('notIn');
        expect(instance.notIn).to.be("Not_in");
      });

    });
  });

}));
